- name: Allow new and established outgoing connections to port 80
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW,ESTABLISHED
    action: insert
	
- name: Allow new and established outgoing connections to port 53
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 53
    ctstate: NEW,ESTABLISHED
    action: insert

- name: Allow established incoming connections to port 53
  iptables:
    chain: INPUT
    protocol: tcp
    source_port: 53
    ctstate: ESTABLISHED
    action: insert

- name: Allow established incoming connections to port 80
  iptables:
    chain: INPUT
    protocol: tcp
    source_port: 80
    ctstate: ESTABLISHED
    action: insert

- name: Allow new and established outgoing connections to port 80
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 443
    ctstate: NEW,ESTABLISHED
    action: insert


- name: Allow established incoming connections to port 80
  iptables:
    chain: INPUT
    protocol: tcp
    source_port: 443
    ctstate: ESTABLISHED
    action: insert
	
- name: Block all outgoing traffic
  iptables:
    chain: OUTPUT
    jump: DROP
    action: insert
