  - name: Install ClamAV basics
    yum: name=clamav state=latest

  - name: Install ClamAV scanner
    yum: name=clamav-scanner state=latest

  - name: Install ClamAV updater
    yum: name=clamav-update state=latest

  - copy:
      src: files/ansible.cron
      dest: /etc/cron.d/ansible.cron
      owner: root
      group: root
      mode: 0644

  - copy:
      src: files/ansible.freshclam
      dest: /etc/freshclam.conf
      owner: root
      group: root
      mode: 0644
